# v0.2

name: VC image deployment
on:
  workflow_dispatch:
    inputs:
      baseImageName:
        description: 'Base kustomize image name'
        required: true
      artifactLink: 
        description: 'Full link to artifact docker image'
        required: true
      appDescriptionRepo:
        description: 'ArgoCd repository'
        required: true
        default: 'VirtoCommerce/vc-webstore-deploy'
      appDescriptionBranch:
        description: 'ArgoCd branch'
        required: true
        default: 'dev'

jobs:
  cd:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

    steps: 
    
    - name: Start deployment
      uses: bobheadxi/deployments@master
      id: deployment
      with:
        step: start
        token: ${{ secrets.GITHUB_TOKEN }}
        env: Development
        no_override: false

    - name: Update deployment-cm
      uses: VirtoCommerce/vc-github-actions/create-deploy-pr@VDS-1269
      with:
        deployRepo: ${{ github.event.inputs.appDescriptionRepo }}
        deployBranch: ${{ github.event.inputs.appDescriptionBranch }}
        artifactKey: ${{ github.event.inputs.moduleId }}
        artifactUrl: ${{ github.event.inputs.blobUrl }}
        taskNumber: "undefined"
        forceCommit: "true"

    - name: Wait for environment is up
      shell: pwsh
      timeout-minutes: 15
      run: | 
        do {
          Start-Sleep -s 15
          $statusBage = (Invoke-WebRequest -Uri "https://argo.govirto.com/api/badge?name=webstore-dev").Content
          
          $syncedAndHealthy = $statusBage.Contains('>Healthy<') -and $statusBage.Contains('>Synced<')
          if (-not $syncedAndHealthy) {
            Write-Host "Sync pending..."
          }
        }
        while (-not $syncedAndHealthy)

    - name: BUILD_STATE::successful
      if: success()
      run: echo "BUILD_STATE=successful" >> $GITHUB_ENV

    - name: BUILD_STATE::failed
      if: failure()
      run: echo "BUILD_STATE=failed"  >> $GITHUB_ENV

    - name: Update GitHub deployment status
      uses: bobheadxi/deployments@master
      if: always()
      with:
        step: finish
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
