# v1.0

name: Deploy Theme to environments
on: 
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'build/**'
      - 'README.md'
      - 'LICENSE'
    branches: [dev]
    types: [labeled, closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      IMAGE_NAME: "demo-storefront"
      ARTIFACT_KEY: "docker.pkg.github.com/virtocommerce/vc-storefront/storefront"

    steps:
    - name: Gets artifact link
      id: artifactLink
      uses: VirtoCommerce/vc-github-actions/get-artifact-link@master

    - name: Create deploy PR in QA
      if: github.event.action != 'closed' && contains(github.event.pull_request.labels.*.name, 'deploy-qa') && !contains(github.event.pull_request.labels.*.name, 'deploy-demo')
      uses: VirtoCommerce/vc-github-actions/create-deploy-pr@VDS-1275
      with:
        deployRepo: "vc-webstore-deploy"
        deployBranch: "qa"
        artifactKey: ${{ env.ARTIFACT_KEY}}
        artifactUrl: "${{ steps.artifactLink.outputs.artifactUrl }}"
        taskNumber: "${{ steps.artifactLink.outputs.qaTaskNumber }}"
        cmPath: "webstore-app/resources/kustomization.yaml"

    - name: Create deploy PR in Demo
      if: github.event.action == 'closed' && github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'deploy-demo')
      uses: VirtoCommerce/vc-github-actions/create-deploy-pr@VDS-1275
      with:
        deployRepo: "vc-webstore-deploy"
        deployBranch: "master"
        artifactKey: ${{ env.ARTIFACT_KEY}}
        artifactUrl: "${{ steps.artifactLink.outputs.artifactUrl }}"
        taskNumber: "${{ steps.artifactLink.outputs.demoTaskNumber }}"
        cmPath: "webstore-app/resources/kustomization.yaml"

    - name: Invoke VC image deployment workflow
#      if: github.event.action == 'closed' && github.event.pull_request.merged == true
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: VC image deployment
        token: ${{ secrets.REPO_TOKEN }}
        inputs: '{ "baseImageName": "docker.pkg.github.com/virtocommerce/vc-storefront/storefront", "artifactLink": "docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ steps.image.outputs.taggedVersion }}"}'
