# v1.0

name: VC image deployment
on:
  workflow_dispatch:
    inputs:
      artifactKey:
        description: 'Module Id or base kustomize image name'
        required: true
      artifactLink: 
        description: 'Full link to artifact docker image or artifact download url'
        required: true
      appName:
        description: 'ArgoCd application name'
        required: true
      appDescriptionRepo:
        description: 'ArgoCd repository'
        required: true
        default: 'vc-webstore-deploy'
      appDescriptionBranch:
        description: 'ArgoCd branch'
        required: true
        default: 'dev'
      cmPath:
        description: "Path to config map or kustomize file in repository"
        required: true

jobs:
  cd:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

    steps: 
    
    - name: Start deployment
      uses: bobheadxi/deployments@master
      id: deployment
      with:
        step: start
        token: ${{ secrets.GITHUB_TOKEN }}
        env: Development
        no_override: false

    - name: Update deployment-cm
      uses: VirtoCommerce/vc-github-actions/create-deploy-pr@VDS-1269
      with:
        deployRepo: ${{ github.event.inputs.appDescriptionRepo }}
        deployBranch: ${{ github.event.inputs.appDescriptionBranch }}
        artifactKey: ${{ github.event.inputs.artifactKey }}
        artifactUrl: ${{ github.event.inputs.artifactLink }}
        taskNumber: "undefined"
        forceCommit: "true"
        cmPath: ${{ github.event.inputs.cmPath }}

    - name: Wait for environment is up
      shell: pwsh
      timeout-minutes: 15
      run: | 
        do {
          Start-Sleep -s 15
          $statusBage = (Invoke-WebRequest -Uri "https://argo.govirto.com/api/badge?name=${{ github.event.inputs.appName }}").Content
          
          $syncedAndHealthy = $statusBage.Contains('>Healthy<') -and $statusBage.Contains('>Synced<')
          if (-not $syncedAndHealthy) {
            Write-Host "Sync pending..."
          }
        }
        while (-not $syncedAndHealthy)

    - name: BUILD_STATE::successful
      if: success()
      run: echo "BUILD_STATE=successful" >> $GITHUB_ENV

    - name: BUILD_STATE::failed
      if: failure()
      run: echo "BUILD_STATE=failed"  >> $GITHUB_ENV

    - name: Update GitHub deployment status
      uses: bobheadxi/deployments@master
      if: always()
      with:
        step: finish
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
