# v1.0

name: test-get-deploy-param
on: 
  workflow_dispatch:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
    steps:
    - name: Read deployment config
      uses: VirtoCommerce/vc-github-actions/get-deploy-param@VDS-1834
      id: deployConfig

    - name: Test output
      shell: bash
      run: echo "${{ steps.deployConfig.outputs.deployConfig}}"